name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - build-images

jobs:
  build-and-push:
    runs-on:
      - ephemeral
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DEVBOX_GCP_ARTIFACT_ADMIN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: us-docker.pkg.dev/dev-staging-308107/devbox-containers/foundationdb
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
